//! Theme module for Rubix-PingPongzz UI.

pub mod dark_theme;

pub use dark_theme::{
    build_visuals, font_definitions, card_margin,
    PRIMARY, PRIMARY_HOVER, SUCCESS, WARNING, ERROR,
    BG, SURFACE, SURFACE_ELEVATED, TEXT_PRIMARY, TEXT_SECONDARY, TEXT_DISABLED,
    BORDER, BORDER_HOVER, SPACING_SMALL, SPACING_MEDIUM, SPACING_LARGE, SPACING_XL,
    RADIUS_SMALL, RADIUS_MEDIUM, RADIUS_LARGE, FONT_SIZE_SMALL, FONT_SIZE_BODY,
    FONT_SIZE_HEADING, FONT_SIZE_TITLE,
};